### ISSUE TITLE
Functions module too big

### ISSUE THREAD

**Issue by iliastsi** [haskell-opengl/OpenGLRaw#33]
The Functions module is too big (nearly 50000 lines of code) causing very high compilation times when using the LLVM code generator. It seems that GHC's LLVM code generator is at fault here, but the compilation times could (significantly) be decreased, if the Functions module were to be split.

The above problem means that OpenGLRaw cannot be built for the arm* architectures on Debian (see also the discussion [here](https://lists.debian.org/debian-haskell/2016/07/msg00002.html)).

Would you consider splitting the Functions module? Feel free to use the code from [here](https://github.com/iliastsi/OpenGLRaw/commit/df9c1b7e3f941a3d) or ask me to do a PR.

**Comment by svenpanne** [comment]
Yes, I think that splitting up the ``Functions`` module into more digestible makes sense. To avoid API breakage, I think the right way to do this is to have various smaller hidden sub-modules, which are in turn re-exported through the old ``Functions`` module. I'll have a look at this...

**Comment by svenpanne** [comment]
I've just [released](../releases/tag/v3.2.1.0) a new version of OpenGLRaw with a chunked Functions module. The changes are based on your patch, with a few differences:

   * I chose 100 API entries per submodule, which results in 200 functions and roughly 1600 lines on average. This should be OK, otherwise the LLVM backend has a *real* problem. If this is still to high, feel free to re-open this issue.
   * The submodules are hidden, so nothing has changed from the outside, including the Haddock docs.
   * I moved some duplicated code to the Foreign module.
   * The OpenGL registry files have been updated, too, so we are back to the very bleeding edge here.
