### ISSUE TITLE
eglGetProcAddress has to be used with OpenGL ES

### ISSUE THREAD

**Issue by KaneTW** [haskell-opengl/OpenGLRaw#35]
OpenGLRaw always uses glXGetProcAddress or variants. This causes failure on recent nvidia drivers with OpenGL ES. Adding 'eglGetProcAddress' to https://github.com/haskell-opengl/OpenGLRaw/blob/master/cbits/HsOpenGLRaw.c#L88 fixes it, but that's a temporary solution.

**Comment by svenpanne** [comment]
Alas, exposing support for both OpenGL and OpenGL ES in a single package doesn't really work. There are at least 3 reasons, mentioned in the fourth item on [the wiki](../wiki/Merging-OpenGLRaw-and-gl#haskell-api).

The right approach would be a new package OpenGLESRaw (covering OpenGL ES versions 2.0 and greater). Note that most of the binding is auto-generated from the OpenGL registry, so this should be doable. Steps:

- Clone/copy the repository to OpenGLESRaw
- Fix directory structure, .cabal file etc. to use the new name
- Use the `gles2` API instead of `gl` for generating the binding. Note: In Khronos-speak even OpenGL 3.x has the `gles2` API, it just has a different `number`.
- Fix all glitches in the API, the `gl` API has quite a few of them, so the `gles2` API is probably not much better.
- Use EGL to retrieve entry points instead of GLX.

I can have a look how much work this actually is, I think it would actually be a useful package nowadays...
