### ISSUE TITLE
glTexParameteri -- 3rf paraameter is defined as GLint, but GL_LINEAR is defined as GLenum

### ISSUE THREAD

**Issue by flajann2** [haskell-opengl/OpenGLRaw#44]
It would seem, if I guess correctly, that there was an attempt to clean up the type of tokens, which is perfectly understandable. However:

in F26.hs

```
-- glTexParameteri -------------------------------------------------------------

-- | Manual pages for <https://www.opengl.org/sdk/docs/man2/xhtml/glTexParameter.xml OpenGL 2.x> or <https://www.opengl.org/sdk/docs/man3/xhtml/glTexParameter.xml OpenGL 3.x> or <https://www.opengl.org/sdk/docs/man4/html/glTexParameter.xhtml OpenGL 4.x>.
glTexParameteri
  :: MonadIO m
  => GLenum -- ^ @target@ of type [TextureTarget](Graphics-GL-Groups.html#TextureTarget).
  -> GLenum -- ^ @pname@ of type [TextureParameterName](Graphics-GL-Groups.html#TextureParameterName).
  -> GLint -- ^ @param@ of type @CheckedInt32@.
  -> m ()
glTexParameteri v1 v2 v3 = liftIO $ dyn66 ptr_glTexParameteri v1 v2 v3

{-# NOINLINE ptr_glTexParameteri #-}
ptr_glTexParameteri :: FunPtr (GLenum -> GLenum -> GLint -> IO ())
ptr_glTexParameteri = unsafePerformIO $ getCommand "glTexParameteri"
```
and in Tokens.hs:

```
src/Graphics/GL/Tokens.hs
4552:pattern GL_LINEAR = 0x2601 :: GLenum
....
```
I surmise that the signature of the function **glTexParameteri** needs to be adjusted?

A similar issue exists with GL_RGB.

Do you want me to make the fixes and submit a PR?  I know a lot of this code is auto-generated, so it may not make sense for me to do it. Please advise. Thank you.

**Comment by svenpanne** [comment]
First of all: Basically all of `OpenGLRaw` is automatically generated from the (horrible) converter below `RegistryProcessor/`, which takes the offifical OpenGL API description at https://github.com/KhronosGroup/OpenGL-Registry/blob/main/xml/gl.xml and generates almost all Haskell code you see here. There are only a few tiny modules like `Graphics.GL.Types` or `Graphics.GL.GetProcAddress` which have been written by hand. So all the function/enum types you see come directly from that API specification, and there is no point in trying to fix the generated code.

A problem problem which has been plaguing the OpenGL API for decades is its sloppy typing: A lot of enums e.g. are used with different types, which is not a real problem in the traditional C binding, since all enums are simply C macros. In Haskell this is a bit more annoying, of course, but there is not really much you can do about it apart from using `fromIntegral` here and there when needed. The problem you're seeing is exactly such a thing: 

```xml
<enum value="0x2601" name="GL_LINEAR" group="BlitFramebufferFilter,FogMode,TextureMagFilter,TextureMinFilter"/>
```

This means that `GL_LINEAR` is used for various things, and in this case even with different types: As a filter for `glBlitFrameBuffer` it's a `GLenum`:

```xml
<command>
    <proto>void <name>glBlitFramebuffer</name></proto>
    <param><ptype>GLint</ptype> <name>srcX0</name></param>
    <param><ptype>GLint</ptype> <name>srcY0</name></param>
    <param><ptype>GLint</ptype> <name>srcX1</name></param>
    <param><ptype>GLint</ptype> <name>srcY1</name></param>
    <param><ptype>GLint</ptype> <name>dstX0</name></param>
    <param><ptype>GLint</ptype> <name>dstY0</name></param>
    <param><ptype>GLint</ptype> <name>dstX1</name></param>
    <param><ptype>GLint</ptype> <name>dstY1</name></param>
    <param group="ClearBufferMask"><ptype>GLbitfield</ptype> <name>mask</name></param>
    <param group="BlitFramebufferFilter"><ptype>GLenum</ptype> <name>filter</name></param>
    <glx type="render" opcode="4330"/>
</command>
```

As a fog mode (and a texture filter) it's used as a `GLint`:
 
```xml
<command>
    <proto>void <name>glFogi</name></proto>
    <param group="FogParameter"><ptype>GLenum</ptype> <name>pname</name></param>
    <param group="CheckedInt32"><ptype>GLint</ptype> <name>param</name></param>
    <glx type="render" opcode="82"/>
</command>
``` 
 
Whatever you will try to fix, the other place will break. And even if there was a fix: It would need to be something in the RegistryProcessor, manually fiddling around with the huge OpenGL API is not sustainable.

**Comment by flajann2** [comment]
I was afraid this would be the case. I know how messy typing anything from the C land can be.  Thanks.
